apiVersion: v1
version: 1.6.0
appVersion: "v6.1.0"
description: Installs the CRDs for snapshot-controller
name: snapshot-controller-crd
type: application
annotations:
  fleet.cattle.io/bundle-id: k3s
