annotations:
  fleet.cattle.io/bundle-id: k3s
apiVersion: v1
appVersion: v6.1.0
description: Installs the CRDs for snapshot-controller
name: snapshot-controller-crd
type: application
version: 1.6.1+up1.6.0
